### ISSUE TITLE
No module named 'nn_model' in train_model.py

### ISSUE THREAD

**Issue by shoda6** [IwasakiLab/Seq2Phase#2]
In the execution "python train_model.py" for the first, The error message below appeared.
```
Traceback (most recent call last):
  File "train_model.py", line 148, in <module>
    main(args.cpu, args.thread, args.less_data, args.client, args.scaffold, args.nonllps)
  File "train_model.py", line 18, in main
    from nn_model import NN
ModuleNotFoundError: No module named 'nn_model'
```

Could you please tell me how to solve this error?
I could not find any packages named nn_model.

**Comment by KMiyata1** [comment]
I apologize for any inconvenience caused by our inattention and for the late reply.
`nn_model.py` has been uploaded.
